[package]
name = "oak-metis"
version.workspace = true
authors.workspace = true
description = "Metis island language parser (CST) for the oak ecosystem"
edition.workspace = true
license.workspace = true
homepage.workspace = true
repository = "https://github.com/yggdrasil-language/oak.rs/tree/master/examples/oak-metis"
documentation = "https://docs.rs/oak-metis"
categories = ["parsing"]
keywords = ["parser", "metis", "island", "cas"]

[dependencies]
oak-core = { workspace = true }
serde = { workspace = true, optional = true }

[dev-dependencies]
oak-testing = { workspace = true }

[features]
default = []
serde = ["dep:serde", "oak-core/serde"]

[package.metadata.docs.rs]
all-features = true
