[package]
name = "oak-pretty-print"
version.workspace = true
authors.workspace = true
description = "Syntax highlighter supporting multiple programming languages."
edition.workspace = true
license.workspace = true
homepage.workspace = true
repository = "https://github.com/yggdrasil-language/oak.rs/tree/master/projects/oak-pretty-print"
documentation = "https://docs.rs/oak-pretty-print"
categories = ["text-processing"]
keywords = ["syntax-highlighting", "code", "highlighting", "multi-language"]

[dependencies]
oak-core = { workspace = true }
oak-macros = { workspace = true }
serde = { workspace = true, optional = true }
serde_json = { workspace = true, optional = true }

[dev-dependencies]
oak-testing = { workspace = true }

[features]
default = ["serde"]
serde = ["dep:serde", "dep:serde_json", "oak-core/serde"]

[package.metadata.docs.rs]
all-features = true
