[package]
name = "oak-lsp"
version.workspace = true
authors.workspace = true
description = "Lightweight LSP types for the Oak framework"
edition.workspace = true
license.workspace = true
homepage.workspace = true
repository = "https://github.com/yggdrasil-language/oak.rs/tree/master/projects/oak-lsp"
categories = ["development-tools"]
keywords = ["lsp", "language-server", "types"]

[dependencies]
axum = { workspace = true, optional = true }
serde = { workspace = true, optional = true }
serde_json = { workspace = true, optional = true }
futures = { workspace = true }
dashmap = { workspace = true }
url = { workspace = true }
oak-core = { workspace = true }
oak-vfs = { workspace = true, features = ["serde"] }
oak-symbols = { workspace = true }
oak-navigation = { workspace = true }
oak-resolver = { workspace = true }
oak-folding = { workspace = true }
tokio = { workspace = true, features = ["io-util", "macros", "sync"] }

[features]
default = [ "serde"]
serde = ["dep:serde", "dep:serde_json", "oak-core/serde", "oak-vfs/serde"]
