[package]
name = "oak-mcp"
version.workspace = true
authors.workspace = true
description = "Oak MCP server with support for compact code structures and fuzzy semantic search."
edition.workspace = true
license.workspace = true
homepage.workspace = true
repository = "https://github.com/ygg-lang/oaks/tree/master/projects/oak-mcp"
categories = ["development-tools"]
keywords = ["mcp", "context-protocol", "ai"]

[dependencies]
tokio = { workspace = true, features = ["rt", "rt-multi-thread", "macros", "sync", "io-util", "time", "io-std"] }
serde = { workspace = true , optional = true }
serde_json = { workspace = true, optional = true }
oak-core = { workspace = true }
oak-lsp = { workspace = true }
oak-vfs = { workspace = true }
oak-symbols = { workspace = true }
oak-hover = { workspace = true }
oak-navigation = { workspace = true }
oak-semantic-search = { workspace = true }
futures = { workspace = true }



[features]
default = ["serde"]
serde = ["dep:serde", "dep:serde_json", "oak-core/serde"]
io-std = ["tokio/io-std"]
