[package]
name = "oak-hover"
version.workspace = true
authors.workspace = true
description = "Hover information and documentation lookup support for the Oak framework."
edition.workspace = true
license.workspace = true
repository = "https://github.com/yggdrasil-language/oak.rs/tree/master/projects/oak-hover"
categories = ["development-tools"]
keywords = ["hover", "documentation", "lsp"]

[dependencies]
oak-core = { workspace = true }
serde = { workspace = true, optional = true }

[features]
default = ["serde"]
serde = ["dep:serde", "oak-core/serde"]
