[package]
name = "oak-python"
version.workspace = true
authors.workspace = true
description = "Hand-written Python frontend"
edition.workspace = true
license.workspace = true
repository = "https://github.com/ygg-lang/oaks/tree/master/examples/oak-python"
categories = ["compilers", "development-tools"]
keywords = ["frontend", "language", "python"]

[dependencies]
oak-core = { workspace = true }
oak-highlight = { workspace = true, optional = true }
oak-pretty-print = { workspace = true, optional = true }
oak-lsp = { workspace = true, optional = true }
oak-hover = { workspace = true, optional = true }
oak-vfs = { workspace = true, optional = true }
oak-mcp = { workspace = true, optional = true }
serde = { workspace = true, optional = true }
futures = { workspace = true, optional = true }
tokio = { workspace = true, optional = true }

[dev-dependencies]
oak-testing = { workspace = true }

[features]
default = ["serde"]
serde = ["dep:serde", "oak-core/serde"]
lsp = ["dep:oak-lsp", "dep:oak-hover", "dep:oak-vfs", "oak-highlight", "oak-pretty-print", "dep:futures"]
mcp = ["lsp", "oak-mcp/io-std"]

[[test]]
name = "main"
required-features = ["serde"]
