[package]
name = "oak-typescript"
version.workspace = true
authors.workspace = true
description = "TypeScript frontend for Oak"
edition.workspace = true
license.workspace = true
repository = "https://github.com/yggdrasil-language/oak.rs/tree/master/examples/oak-typescript"
categories = ["compilers", "development-tools"]
keywords = ["frontend", "language", "typescript"]

[dependencies]
oak-core = { workspace = true }
oak-pretty-print = { workspace = true }
serde = { workspace = true, optional = true }

[features]
default = ["serde"]
serde = ["dep:serde", "oak-core/serde"]

[[test]]
name = "main"
required-features = ["serde"]
