[package]
name = "oak-symbols"
version.workspace = true
authors.workspace = true
description = "Symbol extraction and management for the Oak framework."
edition.workspace = true
license.workspace = true
repository = "https://github.com/yggdrasil-language/oak.rs/tree/master/projects/oak-symbols"
categories = ["development-tools"]
keywords = ["symbols", "extraction", "indexing"]

[dependencies]
oak-core = { workspace = true }
serde = { workspace = true, optional = true }

[features]
default = ["serde"]
serde = ["dep:serde", "oak-core/serde"]
