[package]
name = "oak-testing"
version.workspace = true
authors.workspace = true
description = "Testing utilities for the Oak language toolchain."
edition.workspace = true
license.workspace = true
homepage.workspace = true
repository = "https://github.com/yggdrasil-language/oak.rs/tree/master/projects/oak-testing"

[dependencies]
oak-core = { workspace = true }
serde = { workspace = true , optional = true }
serde_json = { workspace = true, optional = true }
triomphe = { workspace = true }
walkdir = { workspace = true }

[features]
serde = ["dep:serde", "dep:serde_json", "oak-core/serde"]
default = ["serde"]
