[package]
name = "oak-macros"
version.workspace = true
authors.workspace = true
description = "Procedural macros for the Oak framework to simplify parser and AST definition."
edition.workspace = true
license.workspace = true
homepage.workspace = true
repository = "https://github.com/yggdrasil-language/oak.rs/tree/master/projects/oak-macros"
categories = ["development-tools", "rust-patterns"]
keywords = ["macros", "proc-macro", "codegen"]

[lib]
proc-macro = true

[dependencies]
proc-macro2 = { workspace = true }
quote = { workspace = true }
syn = { workspace = true }

[features]
default = []
