[package]
name = "oak-resolver"
version.workspace = true
authors.workspace = true
description = "Module resolution and global symbol management for the Oaks framework."
edition.workspace = true
license.workspace = true
repository = "https://github.com/ygg-lang/oaks/tree/master/projects/oak-resolver"

[dependencies]
oak-core = { workspace = true }
oak-vfs = { workspace = true }
oak-symbols = { workspace = true }
serde = { workspace = true, optional = true }
dashmap = { workspace = true }
url = { workspace = true }

[features]
serde = ["dep:serde", "oak-core/serde"]
default = ["serde"]
