[package]
name = "oak-vfs"
version.workspace = true
authors.workspace = true
description = "Virtual file system abstraction for the Oak framework, supporting disk and memory-based storage."
edition.workspace = true
license.workspace = true
homepage.workspace = true
repository = "https://github.com/yggdrasil-language/oak.rs/tree/master/projects/oak-vfs"
categories = ["filesystem"]
keywords = ["vfs", "filesystem", "virtual"]

[dependencies]
serde = { workspace = true, optional = true }
url = { workspace = true }
walkdir = { workspace = true, optional = true }
oak-core = { workspace = true }
notify = { workspace = true, optional = true }

[features]
default = ["disk", "serde"]
disk = ["dep:walkdir", "dep:notify"]
serde = ["dep:serde", "oak-core/serde"]
