[package]
name = "oak-valkyrie"
version.workspace = true
authors.workspace = true
description = "High-performance incremental Valkyrie parser for the oak ecosystem with flexible configuration."
edition.workspace = true
license.workspace = true
homepage.workspace = true
repository = "https://github.com/ygg-lang/oaks/tree/master/examples/oak-valkyrie"
documentation = "https://docs.rs/oak-valkyrie"
categories = ["parsing"]
keywords = ["parser", "valkyrie", "experimental"]

[dependencies]
oak-core = { workspace = true }
oak-dejavu = { workspace = true }
serde = { workspace = true, optional = true, features = ["unstable"]}
unicode-ident = "1.0.12"

[dev-dependencies]
oak-testing = { workspace = true }

[features]
default = ["serde"]
serde = ["dep:serde", "oak-core/serde"]

[package.metadata.docs.rs]
all-features = true

[[test]]
name = "main"
required-features = ["serde"]

[[test]]
name = "lexer"
path = "tests/lexer/mod.rs"
required-features = ["serde"]
