[package]
name = "oak-ruby"
version.workspace = true
authors.workspace = true
description = "Ruby dynamic programming language parser with support for object-oriented programming and modern Ruby features."
edition.workspace = true
license.workspace = true
homepage.workspace = true
repository = "https://github.com/ygg-lang/oaks/tree/master/examples/oak-ruby"
documentation = "https://docs.rs/oak-ruby"
categories = ["parsing"]
keywords = ["parser", "ruby", "ast", "language"]

[dependencies]
oak-core = { workspace = true }
oak-highlight = { workspace = true, optional = true }
oak-pretty-print = { workspace = true, optional = true }
serde = { workspace = true, optional = true }

[dev-dependencies]
oak-testing = { workspace = true }

walkdir = { workspace = true }

[features]
default = ["serde"]
serde = ["dep:serde", "oak-core/serde"]

[package.metadata.docs.rs]
all-features = true

[[test]]
name = "main"
required-features = ["serde"]
