[package]
name = "oak-structural-view"
version.workspace = true
authors.workspace = true
description = "AST-based document structure and structure generation for the Oak framework."
edition.workspace = true
license.workspace = true
repository = "https://github.com/yggdrasil-language/oak.rs/tree/master/projects/oak-structural-view"
categories = ["development-tools"]
keywords = ["structure", "outline", "ast", "symbols"]

[dependencies]
oak-core = { workspace = true }
serde = { workspace = true, optional = true }

[features]
default = ["serde"]
serde = ["dep:serde", "oak-core/serde"]
