[package]
name = "oak-diagnostic"
version.workspace = true
authors.workspace = true
description = "Beautiful diagnostic reporting for the Oak ecosystem, inspired by miette."
edition.workspace = true
license.workspace = true
homepage = "https://github.com/ygg-lang/oaks"
repository = "https://github.com/ygg-lang/oaks/tree/master/projects/oak-diagnostic"
categories = ["development-tools"]
keywords = ["diagnostic", "error", "reporting", "miette"]

[lib]
path = "src/lib.rs"

[features]
default = ["serde"]
serde = ["dep:serde", "dep:serde_json", "oak-core/serde", "oak-vfs/serde"]

[dependencies]
diagnostic = { workspace = true, default-features = false, features = ["std", "serde"] }
oak-core = { workspace = true }
oak-vfs = { workspace = true }
serde = { workspace = true, optional = true }
serde_json = { workspace = true, optional = true }
